# This file is a working example configuration for testing / debugging.
# You can use this config together with a respective config example for the R-cds2db.

##################################################
# Project Definition for module dataprocessor    #
##################################################

[general]

#################
# VERBOSE LEVELS
#
# VL_00_NOTHING             = 0
# VL_10_MAIN_INFO           = 1
# VL_20_OUTER_SCRIPTS       = 2
# VL_30_INNER_SCRIPTS       = 3
# VL_40_INNER_SCRIPTS_INFOS = 4
# VL_50_TABLES              = 5
# VL_60_ALL_TABLES          = 6
# VL_70_DOWNLOAD            = 7
# VL_80_COI_PROCESSING      = 8
# VL_90_FHIR_RESPONSE       = 9
#################
VERBOSE               = 10 # Retrieval / analysis verbose level

#################
# Set true if every sourcing of the 00_Main file should create result
# directories in the otuputGlobal and otuputLocal directores with a timestamp
# suffix. If false then every run will write in the same subdirectory without
# a timestamp. The default behaviour should write in subdirectories with only
# the project name (false) or in or in a subdirectory with the project name
# and the suffix '_timestamp'. (true)
#################
USE_TIMESTAMP_AS_RESULT_DIR_SUFFIX = false

#################
# Maximum of saved cds2db result folders in outputLocal and outputGlobal
#################
MAX_DIR_COUNT = 5

[analyse]

#################
# In the patient table of the frontend, the patient ID should be displayed, which
# can be used to search for further information on the patient in other systems.
# This is normally specified as one of several possible identifiers for a FHIR
# patient resource. To select the correct one, a string as a grep pattern can be
# specified here for the 'system' entry of the Identifier, 'type/coding/system'
# and/or the 'type/coding/code' of the Identifier, via which the correct one
# can be found.
# These patterns are regular expressions for R
# (see https://hypebright.nl/index.php/en/2020/05/25/ultimate-cheatsheet-for-regex-in-r-2/).
# Exception: If a variable is commented out or the empty string "" then the filter
# on this FHIR expression is deactivated. The same result can be achieved by passing
# ".*" as the pattern, which means "any characters any number of times".
# If the filter result on a single Patient resoruce will provide more than one
# Identifier, then they are written one after the other, separated by semicolons.
# Accepts any system with pattern ".*" (Default).
#################
FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_SYSTEM = ".*"

#################
# Accepts only type/coding/sytem with the exact value 'http://terminology.hl7.org/CodeSystem/v2-0203'
# this system is the binded system for the clinical information system patient ID.
# FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_TYPE_SYSTEM = "^http://terminology.hl7.org/CodeSystem/v2-0203$"
# Alternative variant to accept any value in 'type/coding/system' with pattern ".*" (Default).
#################
FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_TYPE_SYSTEM = ".*"

#################
# Accepts only type/coding/code with the exact value 'MR'. This value means
# 'medical record number' in the system http://terminology.hl7.org/CodeSystem/v2-0203
# and is the recommended code for the patient ID in the hospital.
# For example: FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_TYPE_CODE = "^MR$"
# To match the start and end of the exact value, use caret (^) and dollar ($) symbols.
# Accept any type/coding/code with pattern ".*" (Default).
#################
FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_TYPE_CODE = ".*"

#################
# This pattern can be used to specify what should be displayed in REDCap as the ID of the overall medical case.
# This should usually be an identifier for a 'Einrichtungskontakt'. To find the correct identifier/value, the exact
# string of the corresponding identifier/system must be specified here.
# This variable has a further meaning. To find all sub-encounters of a medical case, the partOf references are
# normally evaluated. If these are not completely available, the identifier/value found here is used as a
# fallback. To do this, all encounters and all sub-encounters must each have this identifier as a common identifier.
# For example: FRONTEND_DISPLAYED_ENCOUNTER_FHIR_IDENTIFIER_SYSTEM = "http://hospitalxy.org/InternalCodeSystem/v1"
#################
FRONTEND_DISPLAYED_ENCOUNTER_FHIR_IDENTIFIER_SYSTEM = ""

#################
# Only Encounters that have one of the entries specified here as a class attribute are displayed
# in the frontend. This match must be exact, i.e. no patterns may be specified here.
# This can be used to ensure that, for example, no outpatient Encounters are displayed even though
# they have not yet ended.
#################
FRONTEND_DISPLAYED_ENCOUNTER_CLASS = ["IMP"]

#################
# This parameter should contain the FHIR element where the name of the room and bed can be found.
# This must be the name of a column in the encounter database table or if the location is a real
# reference to a Location resource, the name of a column in the location table. (see
# Table_Description.xlsx in the cds2db module)
#
# Examples (choose exact one or create your own):
#################
#FRONTEND_DISPLAYED_ROOM_AND_BED_COLUMN = "enc_location_display"
#FRONTEND_DISPLAYED_ROOM_AND_BED_COLUMN = "enc_location_identifier_value"
#FRONTEND_DISPLAYED_ROOM_AND_BED_COLUMN = "loc_name"
#FRONTEND_DISPLAYED_ROOM_AND_BED_COLUMN = "loc_identifier_type_display"

#################
# The codes for height, weight and BMI can be customised here. If several codes
# can occur, these must be entered in the respective list separated by spaces.
#################
OBSERVATION_BODY_WEIGHT_SYSTEM = "http://loinc.org"
OBSERVATION_BODY_WEIGHT_CODES  = "3142-7 29463-7"
OBSERVATION_BODY_HEIGHT_SYSTEM = "http://loinc.org"
OBSERVATION_BODY_HEIGHT_CODES  = "8302-2"
OBSERVATION_BMI_SYSTEM         = "http://loinc.org"
OBSERVATION_BMI_CODES          = "39156-5"

[database]

PATH_TO_DB_CONFIG_TOML = "./cds_hub_db_config.toml"
