# URLs ohne Endungen wie .html oder .md
permalink:        pretty
# Setup
# Themes: minima (taugt nicht, da fehlerhaft)
theme:            jekyll-theme-primer
title:            'CDS Tool Chain'
#tagline:          'MII KDS FHIR -> DB -> Frontend'
#description:      ''
#url:              https://foo.de
#baseurl:          ''

#author:
#  name:           'INTERPOLAR IT-Team'
#  url:            https://github.com/SebStaeubert , https://github.com/astruebi, https://github.com/Flow191, https://github.com/reuschem
