FROM rocker/r-ver:4.5.1

# Select cran mirror

RUN echo 'options(repos = c(CRAN = "https://ftp.fau.de/cran/"))' >>"${R_HOME}/etc/Rprofile.site"

# Number of CPUs to speed up build (unclear, if this has any effect)

ENV NCPUS=1

# R-env

# Utils
RUN apt-get update && apt-get install -y -q \
        apt-utils \
        vim less \
        wget curl

# etlutils

RUN apt-get install -y \
	libssl-dev libcurl4-openssl-dev libpq-dev libxml2-dev libudunits2-dev

RUN /rocker_scripts/bin/install2.r -n $NCPUS memuse
RUN /rocker_scripts/bin/install2.r -n $NCPUS openxlsx
RUN /rocker_scripts/bin/install2.r -n $NCPUS RcppTOML
RUN /rocker_scripts/bin/install2.r -n $NCPUS DBI
RUN /rocker_scripts/bin/install2.r -n $NCPUS lubridate
RUN /rocker_scripts/bin/install2.r -n $NCPUS RPostgres
RUN /rocker_scripts/bin/install2.r -n $NCPUS ICD10gm
RUN /rocker_scripts/bin/install2.r -n $NCPUS data.table
RUN /rocker_scripts/bin/install2.r -n $NCPUS httr
RUN /rocker_scripts/bin/install2.r -n $NCPUS rlang
RUN /rocker_scripts/bin/install2.r -n $NCPUS stringr
RUN /rocker_scripts/bin/install2.r -n $NCPUS xml2
RUN /rocker_scripts/bin/install2.r -n $NCPUS fhircrackr
RUN /rocker_scripts/bin/install2.r -n $NCPUS base64enc
RUN /rocker_scripts/bin/install2.r -n $NCPUS digest
RUN /rocker_scripts/bin/install2.r -n $NCPUS units

# Install R packages for interactive HTML tables
RUN /rocker_scripts/bin/install2.r -n $NCPUS htmlwidgets htmltools DT jsonlite

WORKDIR /src

COPY R-etlutils R-etlutils

RUN R CMD build R-etlutils/etlutils

RUN R CMD INSTALL --preclean --no-multiarch --with-keep.source R-etlutils/etlutils


# cds2db

COPY R-cds2db R-cds2db

RUN R CMD build R-cds2db/cds2db

RUN R CMD INSTALL --preclean --no-multiarch --with-keep.source R-cds2db/cds2db


# db2frontend

RUN apt-get install -y libsodium-dev libsecret-1-0

RUN /rocker_scripts/bin/install2.r -n $NCPUS redcapAPI
RUN /rocker_scripts/bin/install2.r -n $NCPUS dplyr

COPY R-db2frontend R-db2frontend

RUN R CMD build R-db2frontend/db2frontend

RUN R CMD INSTALL --preclean --no-multiarch --with-keep.source R-db2frontend/db2frontend


# DataProcessor

COPY R-dataprocessor R-dataprocessor

RUN R CMD build R-dataprocessor/dataprocessor

RUN R CMD INSTALL --preclean --no-multiarch --with-keep.source R-dataprocessor/dataprocessor

# R-cdstoolchain

COPY R-cdstoolchain R-cdstoolchain


# cleanup

RUN apt-get autoremove && apt-get clean
