--Create SQL View not Typed Datasets in Schema cds2db_out
CREATE OR REPLACE VIEW cds2db_out.v_encounter AS (
   SELECT DISTINCT
      enc_id,
      enc_patient_id,
      enc_partof_id,
      enc_identifier_use,
      enc_identifier_type_system,
      enc_identifier_type_version,
      enc_identifier_type_code,
      enc_identifier_type_display,
      enc_identifier_type_text,
      enc_identifier_system,
      enc_identifier_value,
      enc_identifier_start,
      enc_identifier_end,
      enc_status,
      enc_class_system,
      enc_class_version,
      enc_class_code,
      enc_class_display,
      enc_type_system,
      enc_type_version,
      enc_type_code,
      enc_type_display,
      enc_type_text,
      enc_servicetype_system,
      enc_servicetype_version,
      enc_servicetype_code,
      enc_servicetype_display,
      enc_servicetype_text,
      enc_period_start,
      enc_period_end,
      enc_diagnosis_condition_id,
      enc_diagnosis_use_system,
      enc_diagnosis_use_version,
      enc_diagnosis_use_code,
      enc_diagnosis_use_display,
      enc_diagnosis_use_text,
      enc_diagnosis_rank,
      enc_hospitalization_admitsource_system,
      enc_hospitalization_admitsource_version,
      enc_hospitalization_admitsource_code,
      enc_hospitalization_admitsource_display,
      enc_hospitalization_admitsource_text,
      enc_hospitalization_dischargedisposition_system,
      enc_hospitalization_dischargedisposition_version,
      enc_hospitalization_dischargedisposition_code,
      enc_hospitalization_dischargedisposition_display,
      enc_hospitalization_dischargedisposition_text,
      enc_location_id,
      enc_location_type,
      enc_location_identifier_use,
      enc_location_identifier_type_system,
      enc_location_identifier_type_version,
      enc_location_identifier_type_code,
      enc_location_identifier_type_display,
      enc_location_identifier_type_text,
      enc_location_display,
      enc_location_status,
      enc_location_physicaltype_system,
      enc_location_physicaltype_version,
      enc_location_physicaltype_code,
      enc_location_physicaltype_display,
      enc_location_physicaltype_text,
      enc_serviceprovider_id,
      enc_serviceprovider_type,
      enc_serviceprovider_identifier_use,
      enc_serviceprovider_identifier_type_system,
      enc_serviceprovider_identifier_type_version,
      enc_serviceprovider_identifier_type_code,
      enc_serviceprovider_identifier_type_display,
      enc_serviceprovider_identifier_type_text,
      enc_serviceprovider_display
   FROM (SELECT * FROM db_log.encounter_raw UNION SELECT * FROM cds2db_in.encounter_raw) m
   WHERE m.encounter_id NOT IN (SELECT encounter_raw_id FROM db_log.encounter UNION SELECT encounter_raw_id FROM cds2db_in.encounter)
);

CREATE OR REPLACE VIEW cds2db_out.v_patient AS (
   SELECT DISTINCT
      pat_id,
      pat_identifier_use,
      pat_identifier_type_system,
      pat_identifier_type_version,
      pat_identifier_type_code,
      pat_identifier_type_display,
      pat_identifier_type_text,
      pat_identifier_system,
      pat_identifier_value,
      pat_identifier_start,
      pat_identifier_end,
      pat_name_text,
      pat_name_family,
      pat_name_given,
      pat_gender,
      pat_birthdate,
      pat_address_postalcode
   FROM (SELECT * FROM db_log.patient_raw UNION SELECT * FROM cds2db_in.patient_raw) m
   WHERE m.patient_id NOT IN (SELECT patient_raw_id FROM db_log.patient UNION SELECT patient_raw_id FROM cds2db_in.patient)
);

CREATE OR REPLACE VIEW cds2db_out.v_condition AS (
   SELECT DISTINCT
      con_id,
      con_encounter_id,
      con_patient_id,
      con_identifier_use,
      con_identifier_type_system,
      con_identifier_type_version,
      con_identifier_type_code,
      con_identifier_type_display,
      con_identifier_type_text,
      con_identifier_system,
      con_identifier_value,
      con_identifier_start,
      con_identifier_end,
      con_clinicalstatus_system,
      con_clinicalstatus_version,
      con_clinicalstatus_code,
      con_clinicalstatus_display,
      con_clinicalstatus_text,
      con_verificationstatus_system,
      con_verificationstatus_version,
      con_verificationstatus_code,
      con_verificationstatus_display,
      con_verificationstatus_text,
      con_category_system,
      con_category_version,
      con_category_code,
      con_category_display,
      con_category_text,
      con_severity_system,
      con_severity_version,
      con_severity_code,
      con_severity_display,
      con_severity_text,
      con_code_system,
      con_code_version,
      con_code_code,
      con_code_display,
      con_code_text,
      con_bodysite_system,
      con_bodysite_version,
      con_bodysite_code,
      con_bodysite_display,
      con_bodysite_text,
      con_onsetperiod_start,
      con_onsetperiod_end,
      con_onsetdatetime,
      con_abatementdatetime,
      con_abatementage_value,
      con_abatementage_comparator,
      con_abatementage_unit,
      con_abatementage_system,
      con_abatementage_code,
      con_abatementperiod_start,
      con_abatementperiod_end,
      con_abatementrange_low_value,
      con_abatementrange_low_unit,
      con_abatementrange_low_system,
      con_abatementrange_low_code,
      con_abatementrange_high_value,
      con_abatementrange_high_unit,
      con_abatementrange_high_system,
      con_abatementrange_high_code,
      con_abatementstring,
      con_recordeddate,
      con_recorder_id,
      con_recorder_type,
      con_recorder_identifier_use,
      con_recorder_identifier_type_system,
      con_recorder_identifier_type_version,
      con_recorder_identifier_type_code,
      con_recorder_identifier_type_display,
      con_recorder_identifier_type_text,
      con_recorder_display,
      con_asserter_id,
      con_asserter_type,
      con_asserter_identifier_use,
      con_asserter_identifier_type_system,
      con_asserter_identifier_type_version,
      con_asserter_identifier_type_code,
      con_asserter_identifier_type_display,
      con_asserter_identifier_type_text,
      con_asserter_display,
      con_stage_summary_system,
      con_stage_summary_version,
      con_stage_summary_code,
      con_stage_summary_display,
      con_stage_summary_text,
      con_stage_assessment_id,
      con_stage_assessment_type,
      con_stage_assessment_identifier_use,
      con_stage_assessment_identifier_type_system,
      con_stage_assessment_identifier_type_version,
      con_stage_assessment_identifier_type_code,
      con_stage_assessment_identifier_type_display,
      con_stage_assessment_identifier_type_text,
      con_stage_assessment_display,
      con_stage_type_system,
      con_stage_type_version,
      con_stage_type_code,
      con_stage_type_display,
      con_stage_type_text,
      con_note_authorstring,
      con_note_authorreference_id,
      con_note_authorreference_type,
      con_note_authorreference_identifier_use,
      con_note_authorreference_identifier_type_system,
      con_note_authorreference_identifier_type_version,
      con_note_authorreference_identifier_type_code,
      con_note_authorreference_identifier_type_display,
      con_note_authorreference_identifier_type_text,
      con_note_authorreference_display,
      con_note_time,
      con_note_text
   FROM (SELECT * FROM db_log.condition_raw UNION SELECT * FROM cds2db_in.condition_raw) m
   WHERE m.condition_id NOT IN (SELECT condition_raw_id FROM db_log.condition UNION SELECT condition_raw_id FROM cds2db_in.condition)
);

CREATE OR REPLACE VIEW cds2db_out.v_medication AS (
   SELECT DISTINCT
      med_id,
      med_identifier_use,
      med_identifier_type_system,
      med_identifier_type_version,
      med_identifier_type_code,
      med_identifier_type_display,
      med_identifier_type_text,
      med_identifier_system,
      med_identifier_value,
      med_identifier_start,
      med_identifier_end,
      med_code_system,
      med_code_version,
      med_code_code,
      med_code_display,
      med_code_text,
      med_status,
      med_form_system,
      med_form_version,
      med_form_code,
      med_form_display,
      med_form_text,
      med_amount_numerator_value,
      med_amount_numerator_comparator,
      med_amount_numerator_unit,
      med_amount_numerator_system,
      med_amount_numerator_code,
      med_amount_denominator_value,
      med_amount_denominator_comparator,
      med_amount_denominator_unit,
      med_amount_denominator_system,
      med_amount_denominator_code,
      med_ingredient_strength_numerator_value,
      med_ingredient_strength_numerator_comparator,
      med_ingredient_strength_numerator_unit,
      med_ingredient_strength_numerator_system,
      med_ingredient_strength_numerator_code,
      med_ingredient_strength_denominator_value,
      med_ingredient_strength_denominator_comparator,
      med_ingredient_strength_denominator_unit,
      med_ingredient_strength_denominator_system,
      med_ingredient_strength_denominator_code,
      med_ingredient_itemcodeableconcept_system,
      med_ingredient_itemcodeableconcept_version,
      med_ingredient_itemcodeableconcept_code,
      med_ingredient_itemcodeableconcept_display,
      med_ingredient_itemcodeableconcept_text,
      med_ingredient_itemreference_id,
      med_ingredient_itemreference_type,
      med_ingredient_itemreference_identifier_use,
      med_ingredient_itemreference_identifier_type_system,
      med_ingredient_itemreference_identifier_type_version,
      med_ingredient_itemreference_identifier_type_code,
      med_ingredient_itemreference_identifier_type_display,
      med_ingredient_itemreference_identifier_type_text,
      med_ingredient_itemreference_display,
      med_ingredient_isactive
   FROM (SELECT * FROM db_log.medication_raw UNION SELECT * FROM cds2db_in.medication_raw) m
   WHERE m.medication_id NOT IN (SELECT medication_raw_id FROM db_log.medication UNION SELECT medication_raw_id FROM cds2db_in.medication)
);

CREATE OR REPLACE VIEW cds2db_out.v_medicationrequest AS (
   SELECT DISTINCT
      medreq_id,
      medreq_encounter_id,
      medreq_patient_id,
      medreq_identifier_use,
      medreq_identifier_type_system,
      medreq_identifier_type_version,
      medreq_identifier_type_code,
      medreq_identifier_type_display,
      medreq_identifier_type_text,
      medreq_identifier_system,
      medreq_identifier_value,
      medreq_identifier_start,
      medreq_identifier_end,
      medreq_medicationreference_id,
      medreq_status,
      medreq_statusreason_system,
      medreq_statusreason_version,
      medreq_statusreason_code,
      medreq_statusreason_display,
      medreq_statusreason_text,
      medreq_intend,
      medreq_category_system,
      medreq_category_version,
      medreq_category_code,
      medreq_category_display,
      medreq_category_text,
      medreq_priority,
      medreq_reportedboolean,
      medreq_reportedreference_id,
      medreq_reportedreference_type,
      medreq_reportedreference_identifier_use,
      medreq_reportedreference_identifier_type_system,
      medreq_reportedreference_identifier_type_version,
      medreq_reportedreference_identifier_type_code,
      medreq_reportedreference_identifier_type_display,
      medreq_reportedreference_identifier_type_text,
      medreq_reportedreference_display,
      medreq_medicationcodeableconcept_system,
      medreq_medicationcodeableconcept_version,
      medreq_medicationcodeableconcept_code,
      medreq_medicationcodeableconcept_display,
      medreq_medicationcodeableconcept_text,
      medreq_supportinginformation_id,
      medreq_supportinginformation_type,
      medreq_supportinginformation_identifier_use,
      medreq_supportinginformation_identifier_type_system,
      medreq_supportinginformation_identifier_type_version,
      medreq_supportinginformation_identifier_type_code,
      medreq_supportinginformation_identifier_type_display,
      medreq_supportinginformation_identifier_type_text,
      medreq_supportinginformation_display,
      medreq_authoredon,
      medreq_requester_id,
      medreq_requester_type,
      medreq_requester_identifier_use,
      medreq_requester_identifier_type_system,
      medreq_requester_identifier_type_version,
      medreq_requester_identifier_type_code,
      medreq_requester_identifier_type_display,
      medreq_requester_identifier_type_text,
      medreq_requester_display,
      medreq_reasoncode_system,
      medreq_reasoncode_version,
      medreq_reasoncode_code,
      medreq_reasoncode_display,
      medreq_reasoncode_text,
      medreq_reasonreference_id,
      medreq_reasonreference_type,
      medreq_reasonreference_identifier_use,
      medreq_reasonreference_identifier_type_system,
      medreq_reasonreference_identifier_type_version,
      medreq_reasonreference_identifier_type_code,
      medreq_reasonreference_identifier_type_display,
      medreq_reasonreference_identifier_type_text,
      medreq_reasonreference_display,
      medreq_basedon_id,
      medreq_basedon_type,
      medreq_basedon_identifier_use,
      medreq_basedon_identifier_type_system,
      medreq_basedon_identifier_type_version,
      medreq_basedon_identifier_type_code,
      medreq_basedon_identifier_type_display,
      medreq_basedon_identifier_type_text,
      medreq_basedon_display,
      medreq_note_authorstring,
      medreq_note_authorreference_id,
      medreq_note_authorreference_type,
      medreq_note_authorreference_identifier_use,
      medreq_note_authorreference_identifier_type_system,
      medreq_note_authorreference_identifier_type_version,
      medreq_note_authorreference_identifier_type_code,
      medreq_note_authorreference_identifier_type_display,
      medreq_note_authorreference_identifier_type_text,
      medreq_note_authorreference_display,
      medreq_note_time,
      medreq_note_text,
      medreq_doseinstruc_sequence,
      medreq_doseinstruc_text,
      medreq_doseinstruc_additionalinstruction_system,
      medreq_doseinstruc_additionalinstruction_version,
      medreq_doseinstruc_additionalinstruction_code,
      medreq_doseinstruc_additionalinstruction_display,
      medreq_doseinstruc_additionalinstruction_text,
      medreq_doseinstruc_patientinstruction,
      medreq_doseinstruc_timing_event,
      medreq_doseinstruc_timing_repeat_boundsduration_value,
      medreq_doseinstruc_timing_repeat_boundsduration_comparator,
      medreq_doseinstruc_timing_repeat_boundsduration_unit,
      medreq_doseinstruc_timing_repeat_boundsduration_system,
      medreq_doseinstruc_timing_repeat_boundsduration_code,
      medreq_doseinstruc_timing_repeat_boundsrange_low_value,
      medreq_doseinstruc_timing_repeat_boundsrange_low_unit,
      medreq_doseinstruc_timing_repeat_boundsrange_low_system,
      medreq_doseinstruc_timing_repeat_boundsrange_low_code,
      medreq_doseinstruc_timing_repeat_boundsrange_high_value,
      medreq_doseinstruc_timing_repeat_boundsrange_high_unit,
      medreq_doseinstruc_timing_repeat_boundsrange_high_system,
      medreq_doseinstruc_timing_repeat_boundsrange_high_code,
      medreq_doseinstruc_timing_repeat_boundsperiod_start,
      medreq_doseinstruc_timing_repeat_boundsperiod_end,
      medreq_doseinstruc_timing_repeat_count,
      medreq_doseinstruc_timing_repeat_countmax,
      medreq_doseinstruc_timing_repeat_duration,
      medreq_doseinstruc_timing_repeat_durationmax,
      medreq_doseinstruc_timing_repeat_durationunit,
      medreq_doseinstruc_timing_repeat_frequency,
      medreq_doseinstruc_timing_repeat_frequencymax,
      medreq_doseinstruc_timing_repeat_period,
      medreq_doseinstruc_timing_repeat_periodmax,
      medreq_doseinstruc_timing_repeat_periodunit,
      medreq_doseinstruc_timing_repeat_dayofweek,
      medreq_doseinstruc_timing_repeat_timeofday,
      medreq_doseinstruc_timing_repeat_when,
      medreq_doseinstruc_timing_repeat_offset,
      medreq_doseinstruc_timing_code_system,
      medreq_doseinstruc_timing_code_version,
      medreq_doseinstruc_timing_code_code,
      medreq_doseinstruc_timing_code_display,
      medreq_doseinstruc_timing_code_text,
      medreq_doseinstruc_asneededboolean,
      medreq_doseinstruc_asneededcodeableconcept_system,
      medreq_doseinstruc_asneededcodeableconcept_version,
      medreq_doseinstruc_asneededcodeableconcept_code,
      medreq_doseinstruc_asneededcodeableconcept_display,
      medreq_doseinstruc_asneededcodeableconcept_text,
      medreq_doseinstruc_site_system,
      medreq_doseinstruc_site_version,
      medreq_doseinstruc_site_code,
      medreq_doseinstruc_site_display,
      medreq_doseinstruc_site_text,
      medreq_doseinstruc_route_system,
      medreq_doseinstruc_route_version,
      medreq_doseinstruc_route_code,
      medreq_doseinstruc_route_display,
      medreq_doseinstruc_route_text,
      medreq_doseinstruc_method_system,
      medreq_doseinstruc_method_version,
      medreq_doseinstruc_method_code,
      medreq_doseinstruc_method_display,
      medreq_doseinstruc_method_text,
      medreq_doseinstruc_doseandrate_type_system,
      medreq_doseinstruc_doseandrate_type_version,
      medreq_doseinstruc_doseandrate_type_code,
      medreq_doseinstruc_doseandrate_type_display,
      medreq_doseinstruc_doseandrate_type_text,
      medreq_doseinstruc_doseandrate_doserange_low_value,
      medreq_doseinstruc_doseandrate_doserange_low_unit,
      medreq_doseinstruc_doseandrate_doserange_low_system,
      medreq_doseinstruc_doseandrate_doserange_low_code,
      medreq_doseinstruc_doseandrate_doserange_high_value,
      medreq_doseinstruc_doseandrate_doserange_high_unit,
      medreq_doseinstruc_doseandrate_doserange_high_system,
      medreq_doseinstruc_doseandrate_doserange_high_code,
      medreq_doseinstruc_doseandrate_dosequantity_value,
      medreq_doseinstruc_doseandrate_dosequantity_comparator,
      medreq_doseinstruc_doseandrate_dosequantity_unit,
      medreq_doseinstruc_doseandrate_dosequantity_system,
      medreq_doseinstruc_doseandrate_dosequantity_code,
      medreq_doseinstruc_doseandrate_rateratio_numerator_value,
      medreq_doseinstruc_doseandrate_rateratio_numerator_comparator,
      medreq_doseinstruc_doseandrate_rateratio_numerator_unit,
      medreq_doseinstruc_doseandrate_rateratio_numerator_system,
      medreq_doseinstruc_doseandrate_rateratio_numerator_code,
      medreq_doseinstruc_doseandrate_rateratio_denominator_value,
      medreq_doseinstruc_doseandrate_rateratio_denominator_comparator,
      medreq_doseinstruc_doseandrate_rateratio_denominator_unit,
      medreq_doseinstruc_doseandrate_rateratio_denominator_system,
      medreq_doseinstruc_doseandrate_rateratio_denominator_code,
      medreq_doseinstruc_doseandrate_raterange_low_value,
      medreq_doseinstruc_doseandrate_raterange_low_unit,
      medreq_doseinstruc_doseandrate_raterange_low_system,
      medreq_doseinstruc_doseandrate_raterange_low_code,
      medreq_doseinstruc_doseandrate_raterange_high_value,
      medreq_doseinstruc_doseandrate_raterange_high_unit,
      medreq_doseinstruc_doseandrate_raterange_high_system,
      medreq_doseinstruc_doseandrate_raterange_high_code,
      medreq_doseinstruc_doseandrate_ratequantity_value,
      medreq_doseinstruc_doseandrate_ratequantity_unit,
      medreq_doseinstruc_doseandrate_ratequantity_system,
      medreq_doseinstruc_doseandrate_ratequantity_code,
      medreq_doseinstruc_maxdoseperperiod_numerator_value,
      medreq_doseinstruc_maxdoseperperiod_numerator_comparator,
      medreq_doseinstruc_maxdoseperperiod_numerator_unit,
      medreq_doseinstruc_maxdoseperperiod_numerator_system,
      medreq_doseinstruc_maxdoseperperiod_numerator_code,
      medreq_doseinstruc_maxdoseperperiod_denominator_value,
      medreq_doseinstruc_maxdoseperperiod_denominator_comparator,
      medreq_doseinstruc_maxdoseperperiod_denominator_unit,
      medreq_doseinstruc_maxdoseperperiod_denominator_system,
      medreq_doseinstruc_maxdoseperperiod_denominator_code,
      medreq_doseinstruc_maxdoseperadministration_value,
      medreq_doseinstruc_maxdoseperadministration_unit,
      medreq_doseinstruc_maxdoseperadministration_system,
      medreq_doseinstruc_maxdoseperadministration_code,
      medreq_doseinstruc_maxdoseperlifetime_value,
      medreq_doseinstruc_maxdoseperlifetime_unit,
      medreq_doseinstruc_maxdoseperlifetime_system,
      medreq_doseinstruc_maxdoseperlifetime_code,
      medreq_substitution_reason_system,
      medreq_substitution_reason_version,
      medreq_substitution_reason_code,
      medreq_substitution_reason_display,
      medreq_substitution_reason_text
   FROM (SELECT * FROM db_log.medicationrequest_raw UNION SELECT * FROM cds2db_in.medicationrequest_raw) m
   WHERE m.medicationrequest_id NOT IN (SELECT medicationrequest_raw_id FROM db_log.medicationrequest UNION SELECT medicationrequest_raw_id FROM cds2db_in.medicationrequest)
);

CREATE OR REPLACE VIEW cds2db_out.v_medicationadministration AS (
   SELECT DISTINCT
      medadm_id,
      medadm_encounter_id,
      medadm_patient_id,
      medadm_partof_id,
      medadm_identifier_use,
      medadm_identifier_type_system,
      medadm_identifier_type_version,
      medadm_identifier_type_code,
      medadm_identifier_type_display,
      medadm_identifier_type_text,
      medadm_identifier_system,
      medadm_identifier_value,
      medadm_identifier_start,
      medadm_identifier_end,
      medadm_status,
      medadm_statusreason_system,
      medadm_statusreason_version,
      medadm_statusreason_code,
      medadm_statusreason_display,
      medadm_statusreason_text,
      medadm_category_system,
      medadm_category_version,
      medadm_category_code,
      medadm_category_display,
      medadm_category_text,
      medadm_medicationreference_id,
      medadm_medicationcodeableconcept_system,
      medadm_medicationcodeableconcept_version,
      medadm_medicationcodeableconcept_code,
      medadm_medicationcodeableconcept_display,
      medadm_medicationcodeableconcept_text,
      medadm_supportinginformation_id,
      medadm_supportinginformation_type,
      medadm_supportinginformation_identifier_use,
      medadm_supportinginformation_identifier_type_system,
      medadm_supportinginformation_identifier_type_version,
      medadm_supportinginformation_identifier_type_code,
      medadm_supportinginformation_identifier_type_display,
      medadm_supportinginformation_identifier_type_text,
      medadm_supportinginformation_display,
      medadm_effectivedatetime,
      medadm_effectiveperiod_start,
      medadm_effectiveperiod_end,
      medadm_performer_function_system,
      medadm_performer_function_version,
      medadm_performer_function_code,
      medadm_performer_function_display,
      medadm_performer_function_text,
      medadm_reasoncode_system,
      medadm_reasoncode_version,
      medadm_reasoncode_code,
      medadm_reasoncode_display,
      medadm_reasoncode_text,
      medadm_reasonreference_id,
      medadm_reasonreference_type,
      medadm_reasonreference_identifier_use,
      medadm_reasonreference_identifier_type_system,
      medadm_reasonreference_identifier_type_version,
      medadm_reasonreference_identifier_type_code,
      medadm_reasonreference_identifier_type_display,
      medadm_reasonreference_identifier_type_text,
      medadm_reasonreference_display,
      medadm_request_id,
      medadm_note_authorstring,
      medadm_note_authorreference_id,
      medadm_note_authorreference_type,
      medadm_note_authorreference_identifier_use,
      medadm_note_authorreference_identifier_type_system,
      medadm_note_authorreference_identifier_type_version,
      medadm_note_authorreference_identifier_type_code,
      medadm_note_authorreference_identifier_type_display,
      medadm_note_authorreference_identifier_type_text,
      medadm_note_authorreference_display,
      medadm_note_time,
      medadm_note_text,
      medadm_dosage_text,
      medadm_dosage_site_system,
      medadm_dosage_site_version,
      medadm_dosage_site_code,
      medadm_dosage_site_display,
      medadm_dosage_site_text,
      medadm_dosage_route_system,
      medadm_dosage_route_version,
      medadm_dosage_route_code,
      medadm_dosage_route_display,
      medadm_dosage_route_text,
      medadm_dosage_method_system,
      medadm_dosage_method_version,
      medadm_dosage_method_code,
      medadm_dosage_method_display,
      medadm_dosage_method_text,
      medadm_dosage_dose_value,
      medadm_dosage_dose_unit,
      medadm_dosage_dose_system,
      medadm_dosage_dose_code,
      medadm_dosage_rateratio_numerator_value,
      medadm_dosage_rateratio_numerator_comparator,
      medadm_dosage_rateratio_numerator_unit,
      medadm_dosage_rateratio_numerator_system,
      medadm_dosage_rateratio_numerator_code,
      medadm_dosage_rateratio_denominator_value,
      medadm_dosage_rateratio_denominator_comparator,
      medadm_dosage_rateratio_denominator_unit,
      medadm_dosage_rateratio_denominator_system,
      medadm_dosage_rateratio_denominator_code,
      medadm_dosage_ratequantity_value,
      medadm_dosage_ratequantity_unit,
      medadm_dosage_ratequantity_system,
      medadm_dosage_ratequantity_code
   FROM (SELECT * FROM db_log.medicationadministration_raw UNION SELECT * FROM cds2db_in.medicationadministration_raw) m
   WHERE m.medicationadministration_id NOT IN (SELECT medicationadministration_raw_id FROM db_log.medicationadministration UNION SELECT medicationadministration_raw_id FROM cds2db_in.medicationadministration)
);

CREATE OR REPLACE VIEW cds2db_out.v_medicationstatement AS (
   SELECT DISTINCT
      medstat_id,
      medstat_identifier_use,
      medstat_identifier_type_system,
      medstat_identifier_type_version,
      medstat_identifier_type_code,
      medstat_identifier_type_display,
      medstat_identifier_type_text,
      medstat_identifier_system,
      medstat_identifier_value,
      medstat_identifier_start,
      medstat_identifier_end,
      medstat_encounter_id,
      medstat_patient_id,
      medstat_partof_id,
      medstat_basedon_id,
      medstat_basedon_type,
      medstat_basedon_identifier_use,
      medstat_basedon_identifier_type_system,
      medstat_basedon_identifier_type_version,
      medstat_basedon_identifier_type_code,
      medstat_basedon_identifier_type_display,
      medstat_basedon_identifier_type_text,
      medstat_basedon_display,
      medstat_status,
      medstat_statusreason_system,
      medstat_statusreason_version,
      medstat_statusreason_code,
      medstat_statusreason_display,
      medstat_statusreason_text,
      medstat_category_system,
      medstat_category_version,
      medstat_category_code,
      medstat_category_display,
      medstat_category_text,
      medstat_medicationreference_id,
      medstat_medicationcodeableconcept_system,
      medstat_medicationcodeableconcept_version,
      medstat_medicationcodeableconcept_code,
      medstat_medicationcodeableconcept_display,
      medstat_medicationcodeableconcept_text,
      medstat_effectivedatetime,
      medstat_effectiveperiod_start,
      medstat_effectiveperiod_end,
      medstat_dateasserted,
      medstat_informationsource_id,
      medstat_informationsource_type,
      medstat_informationsource_identifier_use,
      medstat_informationsource_identifier_type_system,
      medstat_informationsource_identifier_type_version,
      medstat_informationsource_identifier_type_code,
      medstat_informationsource_identifier_type_display,
      medstat_informationsource_identifier_type_text,
      medstat_informationsource_display,
      medstat_derivedfrom_id,
      medstat_derivedfrom_type,
      medstat_derivedfrom_identifier_use,
      medstat_derivedfrom_identifier_type_system,
      medstat_derivedfrom_identifier_type_version,
      medstat_derivedfrom_identifier_type_code,
      medstat_derivedfrom_identifier_type_display,
      medstat_derivedfrom_identifier_type_text,
      medstat_derivedfrom_display,
      medstat_reasoncode_system,
      medstat_reasoncode_version,
      medstat_reasoncode_code,
      medstat_reasoncode_display,
      medstat_reasoncode_text,
      medstat_reasonreference_id,
      medstat_reasonreference_type,
      medstat_reasonreference_identifier_use,
      medstat_reasonreference_identifier_type_system,
      medstat_reasonreference_identifier_type_version,
      medstat_reasonreference_identifier_type_code,
      medstat_reasonreference_identifier_type_display,
      medstat_reasonreference_identifier_type_text,
      medstat_reasonreference_display,
      medstat_note_authorstring,
      medstat_note_authorreference_id,
      medstat_note_authorreference_type,
      medstat_note_authorreference_identifier_use,
      medstat_note_authorreference_identifier_type_system,
      medstat_note_authorreference_identifier_type_version,
      medstat_note_authorreference_identifier_type_code,
      medstat_note_authorreference_identifier_type_display,
      medstat_note_authorreference_identifier_type_text,
      medstat_note_authorreference_display,
      medstat_note_time,
      medstat_note_text,
      medstat_dosage_sequence,
      medstat_dosage_text,
      medstat_dosage_additionalinstruction_system,
      medstat_dosage_additionalinstruction_version,
      medstat_dosage_additionalinstruction_code,
      medstat_dosage_additionalinstruction_display,
      medstat_dosage_additionalinstruction_text,
      medstat_dosage_patientinstruction,
      medstat_dosage_timing_event,
      medstat_dosage_timing_repeat_boundsduration_value,
      medstat_dosage_timing_repeat_boundsduration_comparator,
      medstat_dosage_timing_repeat_boundsduration_unit,
      medstat_dosage_timing_repeat_boundsduration_system,
      medstat_dosage_timing_repeat_boundsduration_code,
      medstat_dosage_timing_repeat_boundsrange_low_value,
      medstat_dosage_timing_repeat_boundsrange_low_unit,
      medstat_dosage_timing_repeat_boundsrange_low_system,
      medstat_dosage_timing_repeat_boundsrange_low_code,
      medstat_dosage_timing_repeat_boundsrange_high_value,
      medstat_dosage_timing_repeat_boundsrange_high_unit,
      medstat_dosage_timing_repeat_boundsrange_high_system,
      medstat_dosage_timing_repeat_boundsrange_high_code,
      medstat_dosage_timing_repeat_boundsperiod_start,
      medstat_dosage_timing_repeat_boundsperiod_end,
      medstat_dosage_timing_repeat_count,
      medstat_dosage_timing_repeat_countmax,
      medstat_dosage_timing_repeat_duration,
      medstat_dosage_timing_repeat_durationmax,
      medstat_dosage_timing_repeat_durationunit,
      medstat_dosage_timing_repeat_frequency,
      medstat_dosage_timing_repeat_frequencymax,
      medstat_dosage_timing_repeat_period,
      medstat_dosage_timing_repeat_periodmax,
      medstat_dosage_timing_repeat_periodunit,
      medstat_dosage_timing_repeat_dayofweek,
      medstat_dosage_timing_repeat_timeofday,
      medstat_dosage_timing_repeat_when,
      medstat_dosage_timing_repeat_offset,
      medstat_dosage_timing_code_system,
      medstat_dosage_timing_code_version,
      medstat_dosage_timing_code_code,
      medstat_dosage_timing_code_display,
      medstat_dosage_timing_code_text,
      medstat_dosage_asneededboolean,
      medstat_dosage_asneededcodeableconcept_system,
      medstat_dosage_asneededcodeableconcept_version,
      medstat_dosage_asneededcodeableconcept_code,
      medstat_dosage_asneededcodeableconcept_display,
      medstat_dosage_asneededcodeableconcept_text,
      medstat_dosage_site_system,
      medstat_dosage_site_version,
      medstat_dosage_site_code,
      medstat_dosage_site_display,
      medstat_dosage_site_text,
      medstat_dosage_route_system,
      medstat_dosage_route_version,
      medstat_dosage_route_code,
      medstat_dosage_route_display,
      medstat_dosage_route_text,
      medstat_dosage_method_system,
      medstat_dosage_method_version,
      medstat_dosage_method_code,
      medstat_dosage_method_display,
      medstat_dosage_method_text,
      medstat_dosage_doseandrate_type_system,
      medstat_dosage_doseandrate_type_version,
      medstat_dosage_doseandrate_type_code,
      medstat_dosage_doseandrate_type_display,
      medstat_dosage_doseandrate_type_text,
      medstat_dosage_doseandrate_doserange_low_value,
      medstat_dosage_doseandrate_doserange_low_unit,
      medstat_dosage_doseandrate_doserange_low_system,
      medstat_dosage_doseandrate_doserange_low_code,
      medstat_dosage_doseandrate_doserange_high_value,
      medstat_dosage_doseandrate_doserange_high_unit,
      medstat_dosage_doseandrate_doserange_high_system,
      medstat_dosage_doseandrate_doserange_high_code,
      medstat_dosage_doseandrate_dosequantity_value,
      medstat_dosage_doseandrate_dosequantity_comparator,
      medstat_dosage_doseandrate_dosequantity_unit,
      medstat_dosage_doseandrate_dosequantity_system,
      medstat_dosage_doseandrate_dosequantity_code,
      medstat_dosage_doseandrate_rateratio_numerator_value,
      medstat_dosage_doseandrate_rateratio_numerator_comparator,
      medstat_dosage_doseandrate_rateratio_numerator_unit,
      medstat_dosage_doseandrate_rateratio_numerator_system,
      medstat_dosage_doseandrate_rateratio_numerator_code,
      medstat_dosage_doseandrate_rateratio_denominator_value,
      medstat_dosage_doseandrate_rateratio_denominator_comparator,
      medstat_dosage_doseandrate_rateratio_denominator_unit,
      medstat_dosage_doseandrate_rateratio_denominator_system,
      medstat_dosage_doseandrate_rateratio_denominator_code,
      medstat_dosage_doseandrate_raterange_low_value,
      medstat_dosage_doseandrate_raterange_low_unit,
      medstat_dosage_doseandrate_raterange_low_system,
      medstat_dosage_doseandrate_raterange_low_code,
      medstat_dosage_doseandrate_raterange_high_value,
      medstat_dosage_doseandrate_raterange_high_unit,
      medstat_dosage_doseandrate_raterange_high_system,
      medstat_dosage_doseandrate_raterange_high_code,
      medstat_dosage_doseandrate_ratequantity_value,
      medstat_dosage_doseandrate_ratequantity_unit,
      medstat_dosage_doseandrate_ratequantity_system,
      medstat_dosage_doseandrate_ratequantity_code,
      medstat_dosage_maxdoseperperiod_numerator_value,
      medstat_dosage_maxdoseperperiod_numerator_comparator,
      medstat_dosage_maxdoseperperiod_numerator_unit,
      medstat_dosage_maxdoseperperiod_numerator_system,
      medstat_dosage_maxdoseperperiod_numerator_code,
      medstat_dosage_maxdoseperperiod_denominator_value,
      medstat_dosage_maxdoseperperiod_denominator_comparator,
      medstat_dosage_maxdoseperperiod_denominator_unit,
      medstat_dosage_maxdoseperperiod_denominator_system,
      medstat_dosage_maxdoseperperiod_denominator_code,
      medstat_dosage_maxdoseperadministration_value,
      medstat_dosage_maxdoseperadministration_unit,
      medstat_dosage_maxdoseperadministration_system,
      medstat_dosage_maxdoseperadministration_code,
      medstat_dosage_maxdoseperlifetime_value,
      medstat_dosage_maxdoseperlifetime_unit,
      medstat_dosage_maxdoseperlifetime_system,
      medstat_dosage_maxdoseperlifetime_code
   FROM (SELECT * FROM db_log.medicationstatement_raw UNION SELECT * FROM cds2db_in.medicationstatement_raw) m
   WHERE m.medicationstatement_id NOT IN (SELECT medicationstatement_raw_id FROM db_log.medicationstatement UNION SELECT medicationstatement_raw_id FROM cds2db_in.medicationstatement)
);

CREATE OR REPLACE VIEW cds2db_out.v_observation AS (
   SELECT DISTINCT
      obs_id,
      obs_encounter_id,
      obs_patient_id,
      obs_partof_id,
      obs_identifier_use,
      obs_identifier_type_system,
      obs_identifier_type_version,
      obs_identifier_type_code,
      obs_identifier_type_display,
      obs_identifier_type_text,
      obs_identifier_system,
      obs_identifier_value,
      obs_identifier_start,
      obs_identifier_end,
      obs_basedon_id,
      obs_basedon_type,
      obs_basedon_identifier_use,
      obs_basedon_identifier_type_system,
      obs_basedon_identifier_type_version,
      obs_basedon_identifier_type_code,
      obs_basedon_identifier_type_display,
      obs_basedon_identifier_type_text,
      obs_basedon_display,
      obs_status,
      obs_category_system,
      obs_category_version,
      obs_category_code,
      obs_category_display,
      obs_category_text,
      obs_code_system,
      obs_code_version,
      obs_code_code,
      obs_code_display,
      obs_code_text,
      obs_effectivedatetime,
      obs_issued,
      obs_valuerange_low_value,
      obs_valuerange_low_unit,
      obs_valuerange_low_system,
      obs_valuerange_low_code,
      obs_valuerange_high_value,
      obs_valuerange_high_unit,
      obs_valuerange_high_system,
      obs_valuerange_high_code,
      obs_valueratio_numerator_value,
      obs_valueratio_numerator_comparator,
      obs_valueratio_numerator_unit,
      obs_valueratio_numerator_system,
      obs_valueratio_numerator_code,
      obs_valueratio_denominator_value,
      obs_valueratio_denominator_comparator,
      obs_valueratio_denominator_unit,
      obs_valueratio_denominator_system,
      obs_valueratio_denominator_code,
      obs_valuequantity_value,
      obs_valuequantity_comparator,
      obs_valuequantity_unit,
      obs_valuequantity_system,
      obs_valuequantity_code,
      obs_valuecodableconcept_system,
      obs_valuecodableconcept_version,
      obs_valuecodableconcept_code,
      obs_valuecodableconcept_display,
      obs_valuecodableconcept_text,
      obs_dataabsentreason_system,
      obs_dataabsentreason_version,
      obs_dataabsentreason_code,
      obs_dataabsentreason_display,
      obs_dataabsentreason_text,
      obs_note_authorstring,
      obs_note_authorreference_id,
      obs_note_authorreference_type,
      obs_note_authorreference_identifier_use,
      obs_note_authorreference_identifier_type_system,
      obs_note_authorreference_identifier_type_version,
      obs_note_authorreference_identifier_type_code,
      obs_note_authorreference_identifier_type_display,
      obs_note_authorreference_identifier_type_text,
      obs_note_authorreference_display,
      obs_note_time,
      obs_note_text,
      obs_method_system,
      obs_method_version,
      obs_method_code,
      obs_method_display,
      obs_method_text,
      obs_performer_id,
      obs_performer_type,
      obs_performer_identifier_use,
      obs_performer_identifier_type_system,
      obs_performer_identifier_type_version,
      obs_performer_identifier_type_code,
      obs_performer_identifier_type_display,
      obs_performer_identifier_type_text,
      obs_performer_display,
      obs_referencerange_low_value,
      obs_referencerange_low_unit,
      obs_referencerange_low_system,
      obs_referencerange_low_code,
      obs_referencerange_high_value,
      obs_referencerange_high_unit,
      obs_referencerange_high_system,
      obs_referencerange_high_code,
      obs_referencerange_type_system,
      obs_referencerange_type_version,
      obs_referencerange_type_code,
      obs_referencerange_type_display,
      obs_referencerange_type_text,
      obs_referencerange_appliesto_system,
      obs_referencerange_appliesto_version,
      obs_referencerange_appliesto_code,
      obs_referencerange_appliesto_display,
      obs_referencerange_appliesto_text,
      obs_referencerange_age_low_value,
      obs_referencerange_age_low_unit,
      obs_referencerange_age_low_system,
      obs_referencerange_age_low_code,
      obs_referencerange_age_high_value,
      obs_referencerange_age_high_unit,
      obs_referencerange_age_high_system,
      obs_referencerange_age_high_code,
      obs_referencerange_text,
      obs_hasmember_id,
      obs_hasmember_type,
      obs_hasmember_identifier_use,
      obs_hasmember_identifier_type_system,
      obs_hasmember_identifier_type_version,
      obs_hasmember_identifier_type_code,
      obs_hasmember_identifier_type_display,
      obs_hasmember_identifier_type_text,
      obs_hasmember_display
   FROM (SELECT * FROM db_log.observation_raw UNION SELECT * FROM cds2db_in.observation_raw) m
   WHERE m.observation_id NOT IN (SELECT observation_raw_id FROM db_log.observation UNION SELECT observation_raw_id FROM cds2db_in.observation)
);

CREATE OR REPLACE VIEW cds2db_out.v_diagnosticreport AS (
   SELECT DISTINCT
      diagrep_id,
      diagrep_encounter_id,
      diagrep_patient_id,
      diagrep_partof_id,
      diagrep_identifier_use,
      diagrep_identifier_type_system,
      diagrep_identifier_type_version,
      diagrep_identifier_type_code,
      diagrep_identifier_type_display,
      diagrep_identifier_type_text,
      diagrep_identifier_system,
      diagrep_identifier_value,
      diagrep_identifier_start,
      diagrep_identifier_end,
      diagrep_result_id,
      diagrep_basedon_id,
      diagrep_status,
      diagrep_category_system,
      diagrep_category_version,
      diagrep_category_code,
      diagrep_category_display,
      diagrep_category_text,
      diagrep_code_system,
      diagrep_code_version,
      diagrep_code_code,
      diagrep_code_display,
      diagrep_code_text,
      diagrep_effectivedatetime,
      diagrep_issued,
      diagrep_performer_id,
      diagrep_performer_type,
      diagrep_performer_identifier_use,
      diagrep_performer_identifier_type_system,
      diagrep_performer_identifier_type_version,
      diagrep_performer_identifier_type_code,
      diagrep_performer_identifier_type_display,
      diagrep_performer_identifier_type_text,
      diagrep_performer_display,
      diagrep_conclusion,
      diagrep_conclusioncode_system,
      diagrep_conclusioncode_version,
      diagrep_conclusioncode_code,
      diagrep_conclusioncode_display,
      diagrep_conclusioncode_text
   FROM (SELECT * FROM db_log.diagnosticreport_raw UNION SELECT * FROM cds2db_in.diagnosticreport_raw) m
   WHERE m.diagnosticreport_id NOT IN (SELECT diagnosticreport_raw_id FROM db_log.diagnosticreport UNION SELECT diagnosticreport_raw_id FROM cds2db_in.diagnosticreport)
);

CREATE OR REPLACE VIEW cds2db_out.v_servicerequest AS (
   SELECT DISTINCT
      servreq_id,
      servreq_encounter_id,
      servreq_patient_id,
      servreq_identifier_use,
      servreq_identifier_type_system,
      servreq_identifier_type_version,
      servreq_identifier_type_code,
      servreq_identifier_type_display,
      servreq_identifier_type_text,
      servreq_identifier_system,
      servreq_identifier_value,
      servreq_identifier_start,
      servreq_identifier_end,
      servreq_basedon_id,
      servreq_basedon_type,
      servreq_basedon_identifier_use,
      servreq_basedon_identifier_type_system,
      servreq_basedon_identifier_type_version,
      servreq_basedon_identifier_type_code,
      servreq_basedon_identifier_type_display,
      servreq_basedon_identifier_type_text,
      servreq_basedon_display,
      servreq_status,
      servreq_intent,
      servreq_category_system,
      servreq_category_version,
      servreq_category_code,
      servreq_category_display,
      servreq_category_text,
      servreq_code_system,
      servreq_code_version,
      servreq_code_code,
      servreq_code_display,
      servreq_code_text,
      servreq_authoredon,
      servreq_requester_id,
      servreq_requester_type,
      servreq_requester_identifier_use,
      servreq_requester_identifier_type_system,
      servreq_requester_identifier_type_version,
      servreq_requester_identifier_type_code,
      servreq_requester_identifier_type_display,
      servreq_requester_identifier_type_text,
      servreq_requester_display,
      servreq_performer_id,
      servreq_performer_type,
      servreq_performer_identifier_use,
      servreq_performer_identifier_type_system,
      servreq_performer_identifier_type_version,
      servreq_performer_identifier_type_code,
      servreq_performer_identifier_type_display,
      servreq_performer_identifier_type_text,
      servreq_performer_display,
      servreq_locationcode_system,
      servreq_locationcode_version,
      servreq_locationcode_code,
      servreq_locationcode_display,
      servreq_locationcode_text
   FROM (SELECT * FROM db_log.servicerequest_raw UNION SELECT * FROM cds2db_in.servicerequest_raw) m
   WHERE m.servicerequest_id NOT IN (SELECT servicerequest_raw_id FROM db_log.servicerequest UNION SELECT servicerequest_raw_id FROM cds2db_in.servicerequest)
);

CREATE OR REPLACE VIEW cds2db_out.v_procedure AS (
   SELECT DISTINCT
      proc_id,
      proc_encounter_id,
      proc_patient_id,
      proc_partof_id,
      proc_identifier_use,
      proc_identifier_type_system,
      proc_identifier_type_version,
      proc_identifier_type_code,
      proc_identifier_type_display,
      proc_identifier_type_text,
      proc_identifier_system,
      proc_identifier_value,
      proc_identifier_start,
      proc_identifier_end,
      proc_basedon_id,
      proc_basedon_type,
      proc_basedon_identifier_use,
      proc_basedon_identifier_type_system,
      proc_basedon_identifier_type_version,
      proc_basedon_identifier_type_code,
      proc_basedon_identifier_type_display,
      proc_basedon_identifier_type_text,
      proc_basedon_display,
      proc_status,
      proc_statusreason_system,
      proc_statusreason_version,
      proc_statusreason_code,
      proc_statusreason_display,
      proc_statusreason_text,
      proc_category_system,
      proc_category_version,
      proc_category_code,
      proc_category_display,
      proc_category_text,
      proc_code_system,
      proc_code_version,
      proc_code_code,
      proc_code_display,
      proc_code_text,
      proc_performeddatetime,
      proc_performedperiod_start,
      proc_performedperiod_end,
      proc_reasoncode_system,
      proc_reasoncode_version,
      proc_reasoncode_code,
      proc_reasoncode_display,
      proc_reasoncode_text,
      proc_reasonreference_id,
      proc_reasonreference_type,
      proc_reasonreference_identifier_use,
      proc_reasonreference_identifier_type_system,
      proc_reasonreference_identifier_type_version,
      proc_reasonreference_identifier_type_code,
      proc_reasonreference_identifier_type_display,
      proc_reasonreference_identifier_type_text,
      proc_reasonreference_display,
      proc_note_authorstring,
      proc_note_authorreference_id,
      proc_note_authorreference_type,
      proc_note_authorreference_identifier_use,
      proc_note_authorreference_identifier_type_system,
      proc_note_authorreference_identifier_type_version,
      proc_note_authorreference_identifier_type_code,
      proc_note_authorreference_identifier_type_display,
      proc_note_authorreference_identifier_type_text,
      proc_note_authorreference_display,
      proc_note_time,
      proc_note_text
   FROM (SELECT * FROM db_log.procedure_raw UNION SELECT * FROM cds2db_in.procedure_raw) m
   WHERE m.procedure_id NOT IN (SELECT procedure_raw_id FROM db_log.procedure UNION SELECT procedure_raw_id FROM cds2db_in.procedure)
);

CREATE OR REPLACE VIEW cds2db_out.v_consent AS (
   SELECT DISTINCT
      cons_id,
      cons_patient_id,
      cons_identifier_use,
      cons_identifier_type_system,
      cons_identifier_type_version,
      cons_identifier_type_code,
      cons_identifier_type_display,
      cons_identifier_type_text,
      cons_identifier_system,
      cons_identifier_value,
      cons_identifier_start,
      cons_identifier_end,
      cons_status,
      cons_scope_system,
      cons_scope_version,
      cons_scope_code,
      cons_scope_display,
      cons_scope_text,
      cons_datetime,
      cons_provision_type,
      cons_provision_period_start,
      cons_provision_period_end,
      cons_provision_actor_role_system,
      cons_provision_actor_role_version,
      cons_provision_actor_role_code,
      cons_provision_actor_role_display,
      cons_provision_actor_role_text,
      cons_provision_code_system,
      cons_provision_code_version,
      cons_provision_code_code,
      cons_provision_code_display,
      cons_provision_code_text,
      cons_provision_dataperiod_start,
      cons_provision_dataperiod_end
   FROM (SELECT * FROM db_log.consent_raw UNION SELECT * FROM cds2db_in.consent_raw) m
   WHERE m.consent_id NOT IN (SELECT consent_raw_id FROM db_log.consent UNION SELECT consent_raw_id FROM cds2db_in.consent)
);

CREATE OR REPLACE VIEW cds2db_out.v_location AS (
   SELECT DISTINCT
      loc_id,
      loc_identifier_use,
      loc_identifier_type_system,
      loc_identifier_type_version,
      loc_identifier_type_code,
      loc_identifier_type_display,
      loc_identifier_type_text,
      loc_identifier_system,
      loc_identifier_value,
      loc_identifier_start,
      loc_identifier_end,
      loc_status,
      loc_name,
      loc_description,
      loc_alias
   FROM (SELECT * FROM db_log.location_raw UNION SELECT * FROM cds2db_in.location_raw) m
   WHERE m.location_id NOT IN (SELECT location_raw_id FROM db_log.location UNION SELECT location_raw_id FROM cds2db_in.location)
);

CREATE OR REPLACE VIEW cds2db_out.v_pids_per_ward AS (
   SELECT DISTINCT
      ward_name,
      patient_id
   FROM (SELECT * FROM db_log.pids_per_ward_raw UNION SELECT * FROM cds2db_in.pids_per_ward_raw) m
   WHERE m.pids_per_ward_id NOT IN (SELECT pids_per_ward_raw_id FROM db_log.pids_per_ward UNION SELECT pids_per_ward_raw_id FROM cds2db_in.pids_per_ward)
);



--SQL Role for Views in Schema cds2db_out
GRANT SELECT ON TABLE cds2db_out.v_encounter TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_encounter TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_patient TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_patient TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_condition TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_condition TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_medication TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_medication TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_medicationrequest TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_medicationrequest TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_medicationadministration TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_medicationadministration TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_medicationstatement TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_medicationstatement TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_observation TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_observation TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_diagnosticreport TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_diagnosticreport TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_servicerequest TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_servicerequest TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_procedure TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_procedure TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_consent TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_consent TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_location TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_location TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;

GRANT SELECT ON TABLE cds2db_out.v_pids_per_ward TO cds2db_user;
GRANT SELECT ON TABLE cds2db_out.v_pids_per_ward TO db_user;
GRANT USAGE ON SCHEMA cds2db_out TO cds2db_user;


