-- ########################################################################################################
--
-- This file is generated. Changes should only be made by regenerating the file.
--
-- Rights definition file             : ./Postgres-cds_hub/init/template/User_Schema_Rights_Definition.xlsx
-- Rights definition file last update : 2025-02-21 10:00:28
-- Rights definition file size        : 15641 Byte
--
-- Create SQL Tables in Schema "cds2db_out"
-- Create time: 2025-02-21 10:27:46
-- TABLE_DESCRIPTION:  ./R-cds2db/cds2db/inst/extdata/Table_Description.xlsx[table_description]
-- SCRIPTNAME:  25_adding_historical_raw_records.sql
-- TEMPLATE:  template_adding_historical_records.sql
-- OWNER_USER:  cds2db_user
-- OWNER_SCHEMA:  cds2db_out
-- TAGS:  
-- TABLE_PREFIX:  v_
-- TABLE_POSTFIX:  _raw_last_version
-- RIGHTS:  
-- GRANT_TARGET_USER:  cds2db_user
-- COPY_FUNC_SCRIPTNAME:  
-- COPY_FUNC_TEMPLATE:  
-- COPY_FUNC_NAME:  
-- SCHEMA_2:  cds2db_in
-- TABLE_POSTFIX_2:  _raw
-- SCHEMA_3:  
-- TABLE_POSTFIX_3:  
-- ########################################################################################################

CREATE OR REPLACE FUNCTION db.add_hist_raw_records()
RETURNS TEXT
SECURITY DEFINER
AS $$
DECLARE
    erg VARCHAR;
BEGIN
-- Teilautomatisch erstellt - manuell nacharbeiten - Nachladen zu Patienten
-- cds2db_in.v_patient_raw_last_version Block entfernen
-- cds2db_in.v_medication_raw_last_version Block nach unten nehmen
-- cds2db_in.v_location_raw_last_version Block nach unten nehmen
-- ToDo Error log einbauen

    ---- aus cds2db_out.v_encounter_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.encounter_raw (
-- Temp        encounter_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        encounter_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_encounter_raw_last_version q
-- Temp        WHERE q.enc_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.encounter_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_patient_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.patient_raw (
-- Temp        patient_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        patient_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_patient_raw_last_version q
-- Temp        WHERE q.pat_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.patient_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_condition_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.condition_raw (
-- Temp        condition_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        condition_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_condition_raw_last_version q
-- Temp        WHERE q.con_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.condition_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_medication_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.medication_raw (
-- Temp        medication_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        medication_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_medication_raw_last_version q
-- Temp        WHERE q.med_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.medication_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_medicationrequest_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.medicationrequest_raw (
-- Temp        medicationrequest_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        medicationrequest_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_medicationrequest_raw_last_version q
-- Temp        WHERE q.medreq_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.medicationrequest_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_medicationadministration_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.medicationadministration_raw (
-- Temp        medicationadministration_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        medicationadministration_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_medicationadministration_raw_last_version q
-- Temp        WHERE q.medadm_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.medicationadministration_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_medicationstatement_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.medicationstatement_raw (
-- Temp        medicationstatement_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        medicationstatement_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_medicationstatement_raw_last_version q
-- Temp        WHERE q.medstat_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.medicationstatement_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_observation_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.observation_raw (
-- Temp        observation_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        observation_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_observation_raw_last_version q
-- Temp        WHERE q.obs_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.observation_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_diagnosticreport_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.diagnosticreport_raw (
-- Temp        diagnosticreport_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        diagnosticreport_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_diagnosticreport_raw_last_version q
-- Temp        WHERE q.diagrep_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.diagnosticreport_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_servicerequest_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.servicerequest_raw (
-- Temp        servicerequest_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        servicerequest_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_servicerequest_raw_last_version q
-- Temp        WHERE q.servreq_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.servicerequest_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_procedure_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.procedure_raw (
-- Temp        procedure_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        procedure_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_procedure_raw_last_version q
-- Temp        WHERE q.proc_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.procedure_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_consent_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.consent_raw (
-- Temp        consent_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        consent_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_consent_raw_last_version q
-- Temp        WHERE q.cons_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.consent_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_location_raw_last_version Nachladen zu akt. Patienten --------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.location_raw (
-- Temp        location_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        location_raw_id,
--  !!! Aufzählung der FHIR Spalten fehlt noch !!!
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_location_raw_last_version q
-- Temp        WHERE q.loc_patient_ref IN (SELECT pat_id FROM cds2db_in.patient_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.location_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;


-- Zur Zeit noch statisch -Nachladen Resourcen ohne direkten Patientenbezug

    ---- aus cds2db_out.v_location_raw_last_--------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.location_raw (
-- Temp        location_raw_id,
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        location_raw_id,
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_location_raw_last_version q
-- Temp        WHERE q.loc_id IN (SELECT enc_location_ref FROM cds2db_in.encounter_raw)
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.location_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    ---- aus cds2db_out.v_medication_raw_last_version_--------------------------------------------
-- Temp    SELECT res FROM pg_background_result(pg_background_launch(
-- Temp    'INSERT INTO cds2db_in.medication_raw (
-- Temp        medication_raw_id,
-- Temp        current_dataset_status
-- Temp    )
-- Temp    (
-- Temp	SELECT
-- Temp        medication_raw_id,
-- Temp        ''reimported from database''
-- Temp        FROM cds2db_out.v_medication_raw_last_version q
-- Temp        WHERE q.med_id IN (SELECT medreq_medicationreference_ref FROM cds2db_in.medicationRequest_raw
-- Temp                           UNION SELECT medadm_medicationreference_ref FROM cds2db_in.medicationadministration_raw
-- Temp                           UNION SELECT medstat_medicationreference_ref FROM cds2db_in.medicationstatement_raw
-- Temp                        )
-- Temp        AND q.hash_index_col NOT IN (SELECT hash_index_col FROM cds2db_in.medication_raw)
-- Temp    )'
-- Temp    ))  AS t(res TEXT) INTO erg;

    RETURN 'Ende ohne Funktionsausführung';
END;
$$ LANGUAGE plpgsql;

