<%IF RIGHTS_DEFINITION:TAGS "\bRAW\b" "COMMENT ON COLUMN <%OWNER_SCHEMA%>.<%TABLE_NAME%>.<%COLUMN_NAME%> IS '<%COLUMN_DESCRIPTION%> (varchar)';"%>
<%IF NOT RIGHTS_DEFINITION:TAGS "\bRAW\b" "COMMENT ON COLUMN <%OWNER_SCHEMA%>.<%TABLE_NAME%>.<%COLUMN_NAME%> IS '<%COLUMN_DESCRIPTION%> (<%COLUMN_TYPE%>)';"%>
