DO
$$
BEGIN
    IF EXISTS ( -- do migration
        SELECT 1 FROM db_config.db_parameter WHERE parameter_name='current_migration_flag' AND parameter_value='1'
    ) THEN
--------------------------------------------------------------------
-- Generation of triggers for the frontend tables to set the record ID for records generated by the frontend

<%LOOP_TABS_SUB_cre_trigger_set_id_TABLES%>

--------------------------------------------------------------------
    END IF; -- do migration
END
$$;
