test_that("convertLabUnits converts simple international unit quotients", {
  expect_equal(etlutils::convertLabUnits(1, "mU/L", "U/L"), 0.001)
  expect_equal(etlutils::convertLabUnits(1, "U/L", "mU/L"), 1000)
  expect_equal(etlutils::convertLabUnits(1, "mU/L", "uU/mL"), 1)
  expect_equal(etlutils::convertLabUnits(1, "m[IU]/L", "u[IU]/mL"), 1)
  expect_equal(etlutils::convertLabUnits(1, "m[iU]/L", "u[iU]/mL"), 1)
  expect_equal(etlutils::convertLabUnits(1, "\u00b5U/mL", "mU/L"), 1)
})

test_that("convertLabUnits keeps the international unit fallback narrow", {
  expect_true(is.na(etlutils::convertLabUnits(1, "mm/U", "m/U")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mU/L", "mg/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mfoo/L", "foo/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "/L", "mU/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "/M", "mU/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mM/", "mU/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "m/", "mU/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mM", "mU/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "foo", "mU/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mU/L", "/L")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mU/L", "/M")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mU/L", "mM/")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mU/L", "m/")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mU/L", "mM")))
  expect_true(is.na(etlutils::convertLabUnits(1, "mU/L", "foo")))
  expect_equal(etlutils::convertLabUnits(1, "mU/L", NA), 1)
  expect_equal(etlutils::convertLabUnits(1, "mU/L", ""), 1)
})

test_that("isValidUnit remains tied to units package validation", {
  expect_false(etlutils::isValidUnit("mU/L"))
  expect_false(etlutils::isValidUnit("m[IU]/L"))
  expect_true(etlutils::isValidUnit("mmol/L"))
})
