-------- VIEW <%OWNER_SCHEMA%>.<%TABLE_NAME%> -------------
CREATE OR REPLACE VIEW <%OWNER_SCHEMA%>.<%TABLE_NAME%> AS (
    SELECT * FROM <%SCHEMA_2%>.<%TABLE_NAME_2%> q
    , ( SELECT MAX(COALESCE(i.TABLE_PREFIX_meta_lastupdated, TO_CHAR(i.last_check_datetime,'YYYY-MM-DD HH24:MI:SS'))) AS LAST_VERSION_DATE, i.TABLE_PREFIX_id AS ID FROM <%SCHEMA_2%>.<%TABLE_NAME_2%> i GROUP BY i.TABLE_PREFIX_id) w
    WHERE COALESCE(q.TABLE_PREFIX_meta_lastupdated, TO_CHAR(q.last_check_datetime,'YYYY-MM-DD HH24:MI:SS'))=w.LAST_VERSION_DATE AND q.TABLE_PREFIX_id=w.ID
);
