CREATE OR REPLACE VIEW <%OWNER_SCHEMA%>.<%TABLE_NAME%> AS (
   SELECT DISTINCT * FROM <%SCHEMA_2%>.<%TABLE_NAME_2%> WHERE <%TABLE_NAME_2%>_id NOT IN (SELECT <%TABLE_NAME_2%>_id FROM <%SCHEMA_2%>.<%SIMPLE_TABLE_NAME%>) ORDER BY <%TABLE_NAME_2%>_id
);
