CREATE OR REPLACE VIEW <%OWNER_SCHEMA%>.<%TABLE_NAME%> AS (
   SELECT DISTINCT * FROM <%SCHEMA_2%>.<%TABLE_NAME_2%> r WHERE NOT (EXISTS(SELECT 1 FROM <%SCHEMA_2%>.<%SIMPLE_TABLE_NAME%> t WHERE r.<%TABLE_NAME_2%>_id = t.<%TABLE_NAME_2%>_id)) ORDER BY <%TABLE_NAME_2%>_id
);

