<%IF RIGHTS_DEFINITION:TAGS "\bRAW\b" "<%COLUMN_NAME%> VARCHAR,   -- <%COLUMN_DESCRIPTION%> (VARCHAR)"%>
<%IF NOT RIGHTS_DEFINITION:TAGS "\bRAW\b" "<%COLUMN_NAME%> <%COLUMN_TYPE%>,   -- <%COLUMN_DESCRIPTION%> (<%COLUMN_TYPE%>)"%>
