<%IF TABLE_DESCRIPTION:COLUMN_DESCRIPTION "\bid\b" "CREATE INDEX IF NOT EXISTS idx_<%TABLE_NAME%>_<%COLUMN_NAME%> ON <%OWNER_SCHEMA%>.<%TABLE_NAME%> ( <%COLUMN_NAME%> );"%>
<%IF TABLE_DESCRIPTION:COLUMN_DESCRIPTION "^meta/" "CREATE INDEX IF NOT EXISTS idx_<%TABLE_NAME%>_<%COLUMN_NAME%> ON <%OWNER_SCHEMA%>.<%TABLE_NAME%> ( <%COLUMN_NAME%> );"%>
