
-- Table "<%TABLE_NAME%>" in schema "<%OWNER_SCHEMA%>"
----------------------------------------------------
GRANT TRIGGER ON <%OWNER_SCHEMA%>.<%TABLE_NAME%> TO <%OWNER_USER%>;
GRANT USAGE ON SCHEMA <%OWNER_SCHEMA%> TO <%OWNER_USER%>;
GRANT USAGE ON db.db_seq TO <%OWNER_USER%>;

<%LOOP_DEF_SUB_LOOP_TABS_SUB_cre_table_GRANTS_AND_FUNCS%>

CREATE OR REPLACE FUNCTION <%OWNER_SCHEMA%>.<%TABLE_NAME%>_tr_ins_fkt()
RETURNS TRIGGER AS $$
BEGIN
    -- Enter the current time
    NEW.input_datetime := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER <%TABLE_NAME%>_tr_ins_tr
  BEFORE INSERT
  ON <%OWNER_SCHEMA%>.<%TABLE_NAME%>
  FOR EACH ROW
  EXECUTE PROCEDURE <%OWNER_SCHEMA%>.<%TABLE_NAME%>_tr_ins_fkt();

