CREATE TABLE .... 

-- If seq=1 then
ALTER TABLE <%GRANT_SCHEMA_NAME%>.<%GRANT_TABLE_NAME%> ALTER COLUMN <%GRANT_TABLE_NAME%>_id SET DEFAULT (nextval('<%GRANT_SCHEMA_NAME%>.<%SEQ_NAME%>));

-- Immer für den targetuser
GRANT TRIGGER ON <%GRANT_SCHEMA_NAME%>.<%GRANT_TABLE_NAME%> TO <%TARGET_USER%>;
GRANT USAGE ON SCHEMA <%GRANT_SCHEMA_NAME%> TO <%TARGET_USER%>;
GRANT USAGE ON <%GRANT_SCHEMA_NAME%>.<%GRANT_SCHEMA_NAME%>_seq TO <%TARGET_USER%>;

-- Schleife
GRANT <%RIGHTS%> ON TABLE <%GRANT_SCHEMA_NAME%>.<%GRANT_TABLE_NAME%> TO <%GRANT_TRAGET_USER%>; -- Additional authorizations for testing

CREATE OR REPLACE FUNCTION <%GRANT_SCHEMA_NAME%>.<%GRANT_TABLE_NAME%>_tr_ins_fkt()
RETURNS TRIGGER AS $$
BEGIN
    -- Enter the current time
    NEW.input_datetime := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER <%GRANT_TABLE_NAME%>_tr_ins_tr
  BEFORE INSERT
  ON <%GRANT_SCHEMA_NAME%>.<%GRANT_TABLE_NAME%>
  FOR EACH ROW
  EXECUTE PROCEDURE <%GRANT_SCHEMA_NAME%>.<%GRANT_TABLE_NAME%>_tr_ins_fkt();
