
CREATE OR REPLACE VIEW <%OWNER_SCHEMA%>.<%TABLE_NAME%> as (SELECT * from <%SCHEMA_2%>.<%SIMPLE_TABLENAME%>);
GRANT SELECT ON  <%OWNER_SCHEMA%>.<%TABLE_NAME%> TO <%OWNER_USER%>;
GRANT USAGE ON SCHEMA <%OWNER_SCHEMA%> TO <%OWNER_USER%>;
