
-- Table "<%TABLE_NAME%>" in schema "<%TARGET_SCHEMA%>"
----------------------------------------------------
<%TEMPLATE_SUB_CRE_TABLE_GRANT_ALTER_TABLE%>

GRANT TRIGGER ON <%TARGET_SCHEMA%>.<%TABLE_NAME%> TO <%TARGET_USER%>;
GRANT USAGE ON SCHEMA <%TARGET_SCHEMA%> TO <%TARGET_USER%>;
GRANT USAGE ON <%TARGET_SCHEMA%>.<%TARGET_SCHEMA%>_seq TO <%TARGET_USER%>;

<%TEMPLATE_SUB_CRE_TABLE_GRANT_RIGHTS%>

CREATE OR REPLACE FUNCTION <%TARGET_SCHEMA%>.<%TABLE_NAME%>_tr_ins_fkt()
RETURNS TRIGGER AS $$
BEGIN
    -- Enter the current time
    NEW.input_datetime := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER <%TABLE_NAME%>_tr_ins_tr
  BEFORE INSERT
  ON <%TARGET_SCHEMA%>.<%TABLE_NAME%>
  FOR EACH ROW
  EXECUTE PROCEDURE <%TARGET_SCHEMA%>.<%TABLE_NAME%>_tr_ins_fkt();
